export const items = [
    {
        id: 1,
        img: "images/Product/i007.jpg",
        name: "白紗",
        originPrice: 10000,
        discountPrice: 6660,
        description: "白色織線製成, <br/>高級紗線, <br/>新娘首選",
    },
    {
        id: 2,
        img: "images/Product/i029.jpg",
        name: "黑色晚禮服",
        originPrice: 6000,
        discountPrice: 4800,
        description: "黑色氣質高雅, <br/>喜歡韓系的新娘必選, <br/>袖子設計不焦慮, <br/>整體大方得體",
    },
    {
        id: 3,
        img: "images/Product/i163.jpg",
        name: "紫色小碎花",
        originPrice: null,
        discountPrice: 16000,
        description: "可愛清新風格, <br/>甜美必備, <br/>小碎花設計, <br/>紫色與眾不同",
    },
    {
        id: 4,
        img: "images/Product/i109.jpg",
        name: "攜手走過",
        originPrice: 100000,
        discountPrice: 66000,
        description: "白紗搭配綠地, <br/>空曠背景襯托, <br/>呈現出兩人欲共度未來的感受",
    },
    {
        id: 5,
        img: "images/Product/i216.jpg",
        name: "日光浴",
        originPrice: 23600,
        discountPrice: 23600,
        description: "大太陽底下, <br/>兩人向陽並肩同行, <br/>感受大自然的洗禮",
    },
    {
        id: 6,
        img: "images/Product/i032.jpg",
        name: "公主抱抱",
        originPrice: 6000,
        discountPrice: 2160,
        description: "最甜蜜的互動, <br/>兩人對視而笑, <br/>捧花點綴, <br/>韓系小清新風格",
    },
];